coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true

ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mock.go"
  - "**/generated*.go"
  - "cmd/watchdog/main.go"
  - "internal/bot/bot.go"
