# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hideA88/game-server-watchdog
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - godox
    - wsl
    - mnd
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - lll
          - dupl
          - gocyclo
          - errcheck
          - gosec
      - path: cmd/
        linters:
          - gochecknoinits
      - path: mock
        linters:
          - dupl
          - funlen

issues:
  max-same-issues: 0
  new: false
