# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
# v2ではformattersが独立したセクションに
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixs:
        - github.com/hideA88/game-server-watchdog
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - godox
    - wsl
    - mnd
    # v2で削除されたlinter: gosimple, stylecheck (staticcheckに統合)
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
  rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    - path: main\.go
      linters:
        - funlen
