name: Test, Lint and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

  lint:
    runs-on: ubuntu-latest
    needs: vet
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v2.1.6
        args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    needs: [vet, lint]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic -parallel 2 ./...

    - name: Check if CODECOV_TOKEN is set
      run: |
        if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
          echo "CODECOV_TOKEN is not set"
        else
          echo "CODECOV_TOKEN is set"
        fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
